### PR TITLE
changes order of backers

### PR DESCRIPTION
**Pull request by f1lander**

### CODE REVIEW

**Comment by OisinKyne** [comment]
Did you see this PR? https://github.com/ObolNetwork/obol-site/pull/62

**Comment by f1lander** [comment]
> Did you see this PR? #62

Yes but @Composeus asked me to do this order, which should I keep it?

New order prioritizing a few backers 

image

**Comment by Composeus** [comment]
Update on this issue. We need to add our new validator backers to the list as well. The full list to be added is:

* Stakely
* Cosmostation
* Kukis Global
* Swiss Staking
* Swift Staking
* a41
* Blockscape
* DSRV

With the mix of VCs and validators, lets go back to **an alphabetical ordering** on the list.

Logo files for the validators attached.

Stakely-io full light logo
dark_logo_cosmostation
Kukis Global
Swiss Staking
swift staking logo-white
a41 logo
blockscape_logo
master_white

**Comment by f1lander** [comment]
> Update on this issue. We need to add our new validator backers to the list as well. The full list to be added is:
> 
> * Stakely
> * Cosmostation
> * Kukis Global
> * Swiss Staking
> * Swift Staking
> * a41
> * Blockscape
> * DSRV
> 
> With the mix of VCs and validators, lets go back to **an alphabetical ordering** on the list.
> 
> Logo files for the validators attached.
> 
> Stakely-io full light logo dark_logo_cosmostation Kukis Global Swiss Staking swift staking logo-white a41 logo blockscape_logo master_white

I'm starting to add the new logo, can you add the website of each company?

**Comment by f1lander** [comment]
@Composeus test here, if everything is correct, please comment so I can merge https://deploy-preview-64--obol-landing.netlify.app/

**Review by OisinKyne — CHANGES_REQUESTED** [review]
Some issues to address.

- DSRV is out of order
- A41 should be first not last
- iosg and iex are not in order
- the LAO would be better under L than T. So between IOSG and nascent please. 
- `output-onlinetools.png` isn't the best filename.

**Comment by f1lander** [comment]
> Some issues to address.
> 
> * DSRV is out of order
> * A41 should be first not last
> * iosg and iex are not in order
> * the LAO would be better under L than T. So between IOSG and nascent please.
> * `output-onlinetools.png` isn't the best filename.

I guess this is because of the number 41, I order everything with sort function not by myself > * A41 should be first not last
not sure if I understand this -> `the LAO would be better under L than T. So between IOSG and nascent please.`

**Comment by OisinKyne** [comment]
>  I order everything with the sort function, not by myself

Think we'll have to control it by hand

> Don't understand this:

On netflix or lists of movies for example, you don't list "The Lion King" under T, you list it under L. Found an overly formal link here that describes it https://apastyle.apa.org/blog/alphabetize-nonsignificant-words  

So in this context "The LAO", would get listed as an 'L', and would be earlier in the list. (This is another reason why we need to statically define this array of backers and not let a sort function handle it.)

**Pull request merged**
